-- Total revenue generated by each customers 
SELECT 
c.customer_key,
first_name,
last_name,
SUM(sales_amount) AS total_revenue
FROM gold.fact_sales f 
LEFT JOIN gold.dim_customers c 
ON f.customer_key = c.customer_key
GROUP BY
c.customer_key,
first_name,
last_name
ORDER BY total_revenue DESC  
